<a href="https://colab.research.google.com/github/vinayak2709/machine-Learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x= np.array([1,2,3])
print(x)

[1 2 3]


In [0]:
type(x)

numpy.ndarray

In [0]:
l= [4, 5, 6]
p= np.asarray(l)
type(p)

numpy.ndarray

In [0]:
x=np.eye(3,3)

In [0]:
print

<function print>

In [0]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
x=np.random.random((2,3))

In [0]:
print(x)

[[0.44637649 0.85544432 0.9478969 ]
 [0.67821601 0.1441044  0.17655496]]


In [0]:
transpose=x.T

In [0]:
print(transpose)

[[0.44637649 0.67821601]
 [0.85544432 0.1441044 ]
 [0.9478969  0.17655496]]


In [0]:
y=x.reshape(6,1)

In [0]:
print(y)

[[0.44637649]
 [0.85544432]
 [0.9478969 ]
 [0.67821601]
 [0.1441044 ]
 [0.17655496]]


In [0]:
A=np.arange(5)

In [0]:
print(A)

[0 1 2 3 4]


In [0]:
c=A+A

In [0]:
print(c)

[0 2 4 6 8]


In [0]:
print(A+2)

[2 3 4 5 6]


In [0]:
x=np.floor(np.random.random((2,3))*10)
print(x)

[[1. 2. 8.]
 [1. 2. 2.]]


In [0]:
x=np.floor(6)

In [0]:

print(x)

6.0


In [0]:
p1=np.inner(A,c)
p2=np.outer(A,c)

In [0]:
print(p1)

60


In [0]:
print(p2)

60


In [0]:
print(p2)

[[ 0  0  0  0  0]
 [ 0  2  4  6  8]
 [ 0  4  8 12 16]
 [ 0  6 12 18 24]
 [ 0  8 16 24 32]]


In [0]:
p2=np.outer(A,c)
print(p2)

[[ 0  0  0  0  0]
 [ 0  2  4  6  8]
 [ 0  4  8 12 16]
 [ 0  6 12 18 24]
 [ 0  8 16 24 32]]


In [0]:
A=np.ones((2,3))
B=np.ones((3,2))

In [0]:
np.dot(B.T,A.T)

array([[3., 3.],
       [3., 3.]])

In [0]:
A.sum()

6.0

In [0]:
A.sum(axis=1)

array([3., 3.])

In [0]:
A.sum(axis=0)

array([2., 2., 2.])